"""Scanner models — ScanJob and GeneratedTest."""

from enum import Enum
from typing import TYPE_CHECKING

from sqlalchemy import JSON, Boolean, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin, UUIDMixin

if TYPE_CHECKING:
    pass


class ScanJobStatus(str, Enum):
    """Status of a project scan job."""

    PENDING = "pending"
    SCANNING = "scanning"
    GENERATING = "generating"
    COMPLETED = "completed"
    FAILED = "failed"


class ScanJob(Base, UUIDMixin, TimestampMixin):
    """Tracks a background scan of a project to discover entry points and generate tests."""

    __tablename__ = "scan_jobs"

    project_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
    )
    status: Mapped[ScanJobStatus] = mapped_column(String(20), default=ScanJobStatus.PENDING)

    # Progress tracking
    progress: Mapped[int] = mapped_column(Integer, default=0)        # 0–100
    files_found: Mapped[int] = mapped_column(Integer, default=0)
    entry_points_found: Mapped[int] = mapped_column(Integer, default=0)
    tests_generated: Mapped[int] = mapped_column(Integer, default=0)

    # Resource classification: {"backend": N, "frontend": N, "database": N}
    entry_points_by_type: Mapped[dict | None] = mapped_column(JSON)

    # Discovered structure (provided by Electron pre-scan or built locally)
    discovered_structure: Mapped[dict | None] = mapped_column(JSON)

    error_message: Mapped[str | None] = mapped_column(Text)

    generated_tests: Mapped[list["GeneratedTest"]] = relationship(
        "GeneratedTest",
        back_populates="scan_job",
        cascade="all, delete-orphan",
    )

    def __repr__(self) -> str:
        return f"<ScanJob(id={self.id}, project={self.project_id}, status={self.status})>"


class GeneratedTest(Base, UUIDMixin, TimestampMixin):
    """A test suggestion generated by AI during a project scan."""

    __tablename__ = "generated_tests"

    scan_job_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("scan_jobs.id", ondelete="CASCADE"),
        nullable=False,
    )
    project_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
    )

    test_name: Mapped[str] = mapped_column(String(500), nullable=False)
    test_code: Mapped[str] = mapped_column(Text, nullable=False)
    test_type: Mapped[str] = mapped_column(String(50), default="e2e")
    entry_point: Mapped[str | None] = mapped_column(String(1000))
    content_hash: Mapped[str | None] = mapped_column(String(32))
    accepted: Mapped[bool] = mapped_column(Boolean, default=False)

    scan_job: Mapped["ScanJob"] = relationship("ScanJob", back_populates="generated_tests")

    def __repr__(self) -> str:
        return f"<GeneratedTest(id={self.id}, name={self.test_name})>"
